#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_TEST,
    MUGSHOT_RHYHORN,
    MUGSHOT_CUTIEFLY,
    MUGSHOT_PIKACHU,
    MUGSHOT_MARILL,
    MUGSHOT_CHINCHOU,
    MUGSHOT_ARCANINE,
    MUGSHOT_LURANTIS,
    MUGSHOT_WEAVILE,
    MUGSHOT_DRAGONAIR,
    MUGSHOT_NOIVERN,
    MUGSHOT_MACHAMP,
    MUGSHOT_CHANSEY,
    MUGSHOT_RIOLU,
    MUGSHOT_DITTO,
    MUGSHOT_CORSOLA,
    MUGSHOT_VOLCARONA,
    MUGSHOT_VAPOREON,
    MUGSHOT_MEW,
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    EMOTE_NORMAL = 0,
    EMOTE_ALT,
    EMOTE_HAPPY,
    EMOTE_ELATED,
    EMOTE_ANGRY,
    EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
